"""initial_schema

Revision ID: 7fa681884ba7
Revises:
Create Date: 2026-09-24 18:45:34.031390

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7fa681884ba7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Extensions specified in ARCHITECTURE.md
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("strava_athlete_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=False),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text(
                '\'{"notifications_enabled": true, "weather_enrichment": true}\'::jsonb'
            ),
            nullable=False,
        ),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("strava_athlete_id"),
        sa.UniqueConstraint("telegram_chat_id"),
    )
    op.create_index("idx_users_strava_athlete", "users", ["strava_athlete_id"], unique=False)
    op.create_index(
        "idx_users_telegram_chat",
        "users",
        ["telegram_chat_id"],
        unique=False,
        postgresql_where=sa.text("telegram_chat_id IS NOT NULL"),
    )
    op.create_table(
        "bikes",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("strava_gear_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "bike_type",
            sa.Enum("road", "gravel", "mtb", "ebike", "commuter", "tt", name="bike_type_enum"),
            server_default=sa.text("'road'"),
            nullable=False,
        ),
        sa.Column("brand", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("total_distance_m", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "total_elevation_m", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("strava_gear_id"),
    )
    op.create_index("idx_bikes_user_active", "bikes", ["user_id", "is_active"], unique=False)
    op.create_table(
        "activities",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("bike_id", sa.UUID(), nullable=True),
        sa.Column("strava_activity_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "activity_type", sa.String(length=50), server_default=sa.text("'Ride'"), nullable=False
        ),
        sa.Column("distance_m", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("moving_time_s", sa.Integer(), nullable=False),
        sa.Column(
            "total_elevation_m",
            sa.Numeric(precision=10, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column("start_latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("start_longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "is_weather_enriched", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("weather_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["bike_id"], ["bikes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("strava_activity_id"),
    )
    op.create_index(
        "idx_activities_bike_start",
        "activities",
        ["bike_id", sa.literal_column("start_time DESC")],
        unique=False,
    )
    op.create_index(
        "idx_activities_pending_weather",
        "activities",
        ["id"],
        unique=False,
        postgresql_where=sa.text("is_weather_enriched = false"),
    )
    op.create_table(
        "components",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("bike_id", sa.UUID(), nullable=False),
        sa.Column(
            "component_type",
            sa.Enum(
                "chain",
                "cassette",
                "chainring",
                "front_brake_pad",
                "rear_brake_pad",
                "front_rotor",
                "rear_rotor",
                "front_tire",
                "rear_tire",
                "bottom_bracket",
                "cables",
                "suspension_fork",
                "rear_shock",
                name="component_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("brand_model", sa.String(length=150), nullable=False),
        sa.Column("lifespan_wear_points", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "current_wear_points",
            sa.Numeric(precision=10, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "optimal",
                "attention_needed",
                "replace_recommended",
                "retired",
                name="component_status_enum",
            ),
            server_default=sa.text("'new'"),
            nullable=False,
        ),
        sa.Column(
            "installed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.CheckConstraint("current_wear_points >= 0", name="chk_positive_wear"),
        sa.CheckConstraint("lifespan_wear_points > 0", name="chk_positive_lifespan"),
        sa.ForeignKeyConstraint(["bike_id"], ["bikes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_components_active_wear",
        "components",
        ["bike_id", "current_wear_points", "lifespan_wear_points"],
        unique=False,
    )
    op.create_index("idx_components_bike_status", "components", ["bike_id", "status"], unique=False)
    op.create_table(
        "activity_component_wear",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("activity_id", sa.UUID(), nullable=False),
        sa.Column("component_id", sa.UUID(), nullable=False),
        sa.Column("wear_delta", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("base_distance_km", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column(
            "elevation_factor",
            sa.Numeric(precision=4, scale=2),
            server_default=sa.text("1.00"),
            nullable=False,
        ),
        sa.Column(
            "weather_factor",
            sa.Numeric(precision=4, scale=2),
            server_default=sa.text("1.00"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["component_id"], ["components.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("activity_id", "component_id", name="uq_activity_component"),
    )
    op.create_index(
        "idx_wear_component_activity",
        "activity_component_wear",
        ["component_id", "activity_id"],
        unique=False,
    )
    op.create_table(
        "maintenance_logs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("component_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "log_type",
            sa.Enum(
                "clean_and_lube",
                "inspect_tune",
                "repair",
                "replace",
                "season_prep",
                name="maintenance_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "cost", sa.Numeric(precision=8, scale=2), server_default=sa.text("0.00"), nullable=True
        ),
        sa.Column("odometer_km", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "performed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["component_id"], ["components.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_logs_component_performed",
        "maintenance_logs",
        ["component_id", sa.literal_column("performed_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_logs_component_performed", table_name="maintenance_logs")
    op.drop_table("maintenance_logs")
    op.drop_index("idx_wear_component_activity", table_name="activity_component_wear")
    op.drop_table("activity_component_wear")
    op.drop_index("idx_components_bike_status", table_name="components")
    op.drop_index("idx_components_active_wear", table_name="components")
    op.drop_table("components")
    op.drop_index(
        "idx_activities_pending_weather",
        table_name="activities",
        postgresql_where=sa.text("is_weather_enriched = false"),
    )
    op.drop_index("idx_activities_bike_start", table_name="activities")
    op.drop_table("activities")
    op.drop_index("idx_bikes_user_active", table_name="bikes")
    op.drop_table("bikes")
    op.drop_index(
        "idx_users_telegram_chat",
        table_name="users",
        postgresql_where=sa.text("telegram_chat_id IS NOT NULL"),
    )
    op.drop_index("idx_users_strava_athlete", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###

    # Drop custom PostgreSQL ENUM types to prevent orphan dependencies
    op.execute("DROP TYPE IF EXISTS maintenance_type_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS component_status_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS component_type_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS bike_type_enum CASCADE")
