"""make strava fields nullable for telegram user

Revision ID: 55404d0c869c
Revises: 7fa681884ba7
Create Date: 2026-09-25 13:56:10.567130

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "55404d0c869c"
down_revision: str | None = "7fa681884ba7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "strava_athlete_id", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("users", "access_token", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("users", "refresh_token", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "users",
        "token_expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "token_expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column("users", "refresh_token", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("users", "access_token", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("users", "strava_athlete_id", existing_type=sa.BIGINT(), nullable=False)
    # ### end Alembic commands ###
